#pragma once

//Quantities displayable on screen
enum MESHDISPLAY_ {
	MESHDISPLAY_NONE = 0, MESHDISPLAY_SM_DEMAG, MESHDISPLAY_SM_OERSTED, MESHDISPLAY_SM_STRAYH,
	MESHDISPLAY_MAGNETIZATION, MESHDISPLAY_EFFECTIVEFIELD,
	MESHDISPLAY_CURRDENSITY, MESHDISPLAY_VOLTAGE, MESHDISPLAY_ELCOND, MESHDISPLAY_SACCUM, MESHDISPLAY_JSX, MESHDISPLAY_JSY, MESHDISPLAY_JSZ, MESHDISPLAY_TS, MESHDISPLAY_TSI,
	MESHDISPLAY_TEMPERATURE, MESHDISPLAY_PARAMVAR, MESHDISPLAY_ROUGHNESS
};

//mesh types
enum MESH_ { MESH_SUPERMESH = 0, MESH_FERROMAGNETIC, MESH_DIPOLE, MESH_METAL, MESH_INSULATOR };
